version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command:
            pip install -r requirements.txt      
      - run:
          name: Run Unit Tests
          command:
            ls
            pytest --html=report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests
    
